steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "Dockerfile"
      - "-t"
      - "gcr.io/$PROJECT_ID/arilo-backend-staging:$BUILD_ID"
      - "-t"
      - "gcr.io/$PROJECT_ID/arilo-backend-staging:latest"
      - "."
    id: "build-arilo-backend"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/arilo-backend-staging:$BUILD_ID"
    id: "push-arilo-backend"
    waitFor: ["build-arilo-backend"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "arilo-backend-staging"
      - "--image"
      - "gcr.io/$PROJECT_ID/arilo-backend-staging:$BUILD_ID"
      - "--region"
      - "asia-south1"
      - "--platform"
      - "managed"
      - "--service-account"
      - "$PROJECT_NUMBER-compute@developer.gserviceaccount.com"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--memory"
      - "1Gi"
      - "--cpu"
      - "1"
      - "--max-instances"
      - "3"
      - "--concurrency"
      - "80"
      - "--timeout"
      - "300"
      - "--add-cloudsql-instances"
      - "documind-474519:asia-south1:arilo-pg-staging"
      - "--set-env-vars"
      - "ARILO_BACKEND_CORS_ALLOWED_ORIGINS=http://localhost:5173"
      - "--set-env-vars"
      - "ARILO_BACKEND_DB_USERNAME=db_user"
      - "--set-env-vars"
      - "ARILO_BACKEND_DB_PASSWORD=db_password"
      - "--set-secrets"
      - "ARILO_BACKEND_DB_URL=ARILO_BACKEND_STAGING_DB_URL_STAGING:latest"
      - "--set-secrets"
      - "ARILO_BACKEND_GOOGLE_CLIENT_ID=ARILO_BACKEND_GOOGLE_CLIENT_ID_STAGING:latest"
      - "--set-secrets"
      - "ARILO_BACKEND_GOOGLE_CLIENT_SECRET=ARILO_BACKEND_GOOGLE_CLIENT_SECRET_STAGING:latest"
      - "--set-secrets"
      - "ARILO_BACKEND_GOOGLE_SCOPE=ARILO_BACKEND_GOOGLE_SCOPE_STAGING:latest"
      - "--set-secrets"
      - "ARILO_BACKEND_GCS_BUCKET_NAME=ARILO_BACKEND_GCS_BUCKET_NAME_STAGING:latest"
      - "--set-secrets"
      - "ARILO_BACKEND_GCS_PROJECT_ID=ARILO_BACKEND_GCS_PROJECT_ID_STAGING:latest"
      - "--set-secrets"
      - "ARILO_BACKEND_MULTIPART_MAX_FILE_SIZE=ARILO_BACKEND_MULTIPART_MAX_FILE_SIZE_STAGING:latest"
      - "--set-secrets"
      - "ARILO_BACKEND_MULTIPART_MAX_REQUEST_SIZE=ARILO_BACKEND_MULTIPART_MAX_REQUEST_SIZE_STAGING:latest"
      - "--set-secrets"
      - "ARILO_BACKEND_MAX_SWALLOW_SIZE=ARILO_BACKEND_MAX_SWALLOW_SIZE_STAGING:latest"
      - "--set-secrets"
      - "ARILO_BACKEND_MAX_HTTP_FORM_POST_SIZE=ARILO_BACKEND_MAX_HTTP_FORM_POST_SIZE_STAGING:latest"
      - "--set-secrets"
      - "ARILO_BACKEND_LOGGING_LEVEL=ARILO_BACKEND_LOGGING_LEVEL_STAGING:latest"
      - "--set-secrets"
      - "ARILO_BACKEND_LOGGING_LEVEL_GOOGLE_CLOUD=ARILO_BACKEND_LOGGING_LEVEL_GOOGLE_CLOUD_STAGING:latest"
      - "--set-secrets"
      - "ARILO_BACKEND_PUBSUB_TOPIC_NAME=ARILO_BACKEND_PUBSUB_TOPIC_NAME_STAGING:latest"
    id: "deploy-arilo-backend"
    waitFor: ["push-arilo-backend"]

images:
  - "gcr.io/$PROJECT_ID/arilo-backend-staging:$BUILD_ID"
  - "gcr.io/$PROJECT_ID/arilo-backend-staging:latest"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  diskSizeGb: 10

timeout: 3600s